npm-tools: Exit early on private packages

diff --git a/packages/npm-tools/scripts/valu-npm-prerelease b/packages/npm-tools/scripts/valu-npm-prerelease
--- a/packages/npm-tools/scripts/valu-npm-prerelease
+++ b/packages/npm-tools/scripts/valu-npm-prerelease
@@ -20,6 +20,13 @@ if [ ! -f package.json ]; then
     exit 1
 fi
 
+if [ "$(jq -r .private package.json)" = "true" ]; then
+    echo
+    echo "Cannot publish a private package"
+    echo
+    exit 1
+fi
+
 
 if [ "$(git status . --porcelain)" != "" ]; then
     echo
