workflow++

diff --git a/.github/workflows/npm-release.yml b/.github/workflows/npm-release.yml
--- a/.github/workflows/npm-release.yml
+++ b/.github/workflows/npm-release.yml
@@ -39,11 +39,17 @@ jobs:
                     release_mode=prerelease
                   fi
 
+
                   prev_tag="$(git describe --abbrev=0 --match "$pkg/v*" || true)"
                   prev_version=$(echo "$prev_tag" | sed -E "s/.+v([0-9\.]+)\$/\1/")
 
                   link_ver="$(echo $next_version | tr -cd '[:alnum:]')"
                   changelog_link="https://github.com/valu-digital/npm-packages/blob/master/packages/$pkg/CHANGELOG.md#v${link_ver}"
+
+                  if [ "$next_version" = "$prev_version" ]; then
+                    echo "Cannot release $prev_version again"
+                    exit 9
+                  fi
 
                   set -x
                   echo "pkg=$pkg" >> $GITHUB_ENV
@@ -71,7 +77,7 @@ jobs:
               with:
                   node-version: "14.x"
 
-            - name: "Build ${{ env.package }}"
+            - name: "Build ${{ env.pkg }}"
               run: |
                   . .github/npm-release.sh
 
